config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :cities, only: [:index, :show]
  mount Sidekiq::Web => '/sidekiq'

  root to: 'cities#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/city.rb
class City < ApplicationRecord
  has_many :pollution_data, dependent: :destroy

  def self.find_or_initialize_by_name(name:)
    city = City.find_by(name: name.capitalize)

    return city if city.present?

    response = fetch_city_data(name)
    build_city_from_response(response) if response.present?
  end

  def self.fetch_city_data(name)
    OpenWeatherService.new.fetch_city(name)
  end

  def self.build_city_from_response(response)
    city_data = response[0]

    City.new(
      name: city_data['name'],
      latitude: city_data['lat'],
      longitude: city_data['lon'],
      country: city_data['country'],
      state: city_data['state']
    )
  end
end

app/models/pollution_datum.rb
class PollutionDatum < ApplicationRecord
  extend ActiveRecord::Import

  belongs_to :city
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  before_action :set_city, only: [:show]

  def index
    @cities = City.all
    @average_aqi_per_state = calculate_average_aqi_per_state
  end

  def show
    @monthly_avg_aqi_per_location = calculate_monthly_avg_aqi_per_location
    @average_aqi_per_location = calculate_average_aqi_per_location
  end

  private

  def set_city
    @city = City.includes(:pollution_data).find(params[:id])
  end

  def calculate_average_aqi_per_state
    City.joins(:pollution_data)
        .select("cities.state AS state_name, AVG(pollution_data.data_index) AS avg_aqi")
        .group("cities.state")
  end

  def calculate_monthly_avg_aqi_per_location
    City.joins(:pollution_data)
        .where(id: @city)
        .select("EXTRACT(MONTH FROM TO_TIMESTAMP(pollution_data.timestamp)) AS month, AVG(pollution_data.data_index) AS avg_aqi")
        .group("EXTRACT(MONTH FROM TO_TIMESTAMP(pollution_data.timestamp))")
  end

  def calculate_average_aqi_per_location
    City.joins(:pollution_data)
        .where(id: @city)
        .select("cities.id, AVG(pollution_data.data_index) AS avg_aqi")
        .group("cities.id")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/views/cities/_city.html.erb
<div class="w-2/6 rounded-lg bg-emerald-300 m-5" id="<%= dom_id city %>">
  <div class="px-4 py-5 sm:px-6">
    <h3 class="text-base font-semibold leading-6 text-gray-900"><%= city.name %>, <%= city.state %>, <%= city.country %></h3>
    <h3 class="text-base font-semibold leading-6 text-gray-900">Latitude: <%= city.latitude %>, Longitude: <%= city.longitude %></h3>
    <h3 class="text-base font-semibold leading-6 text-gray-900">Latest Air Quality Index: <%= city.pollution_data.last.data_index %></h3>
  </div>
  <% if action_name != "show" %>
    <%= link_to "Show this pollution data", city, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium mb-10" %>
  <% end %>
</div>

app/views/cities/index.html.erb
<div class="w-full mt-10">
  <h1 class="text-base text-2xl font-semibold text-gray-900">Average AQI per State:</h1>
  </br>
  <% @average_aqi_per_state.each do |data| %>
    <p><%= data.state_name %> | Average AQI: <%= data.avg_aqi.round(2) %></p>
  <% end %>
  <br>
  <h1 class="text-base text-2xl font-semibold text-gray-900">All Cities</h1>
  <div id="cities" class="flex flex-wrap justify-center">
    <%= render @cities %>
  </div>
</div>

app/views/cities/search.html.erb
<div>
  <h1 class="font-bold text-4xl">Cities#search</h1>
  <p>Find me in app/views/cities/search.html.erb</p>
</div>

app/views/cities/show.html.erb
<div class="mt-8">
  <div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
    <div class="sm:flex sm:items-center">
      <div class="sm:flex-auto">
        <h1 class="text-base font-semibold text-gray-900">
          <%= @city.name %>, <%= @city.state %>, <%= @city.country %>
        </h1>
        <p class="mt-2 text-sm text-gray-700"></p>
        </br>
        <h1 class="text-base text-2xl font-semibold text-gray-900">Month wise average AQI for the <%= @city.name %></h1>
        <% @monthly_avg_aqi_per_location.each do |data| %>
          <p> Average AQI for <%= Date::MONTHNAMES[data.month] %>: <%= data.avg_aqi.round(2) %></p>
        <% end %>
        </br>
        <p><h1 class="text-base text-2xl font-semibold text-gray-900">Average AQI for the <%= @city.name %>:</h1> <%= @average_aqi_per_location.first.avg_aqi.round(2) %></p>

      </div>
    </div>
  </div>
  <div class="mt-8 flow-root overflow-hidden">
    <div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
      <table class="w-full text-left">
        <thead class="bg-white">
          <tr>
            <th scope="col" class="relative isolate py-3.5 pr-3 text-left text-sm font-semibold text-gray-900">
              Index
              <div class="absolute inset-y-0 right-full -z-10 w-screen border-b border-b-gray-200"></div>
              <div class="absolute inset-y-0 left-0 -z-10 w-screen border-b border-b-gray-200"></div>
            </th>
            <th scope="col" class="hidden px-3 py-3.5 text-left text-sm font-semibold text-gray-900 sm:table-cell">Carbon Monoxide</th>
            <th scope="col" class="hidden px-3 py-3.5 text-left text-sm font-semibold text-gray-900 md:table-cell">Nitric Oxide</th>
            <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Nitrogen Dioxide</th>
            <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Ozone</th>
            <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Sulfur Dioxide</th>
            <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Particulate Matter 2.5</th>
            <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Particulate Matter 10</th>
            <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Ammonia</th>
            <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Timestamp</th>
          </tr>
        </thead>
        <tbody>
          <%= render @city.pollution_data %>
        </tbody>
      </table>
    </div>
  </div>
  <%= link_to "Back to Cities", cities_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AirPollutionTracker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <main class="text-center flex justify-center ">
      <%= yield %>
    </main>
  </body>
</html>

app/views/pollution_data/_pollution_datum.html.erb
<tr id="<%= dom_id pollution_datum %>">
  <td class="relative py-4 pr-3 text-sm font-medium text-gray-900">
    <%= pollution_datum.data_index %>
    <div class="absolute bottom-0 right-full h-px w-screen bg-gray-100"></div>
    <div class="absolute bottom-0 left-0 h-px w-screen bg-gray-100"></div>
  </td>
  <td class="px-3 py-4 text-sm text-gray-500"><%= pollution_datum.carbon_monoxide %></td>
  <td class="hidden px-3 py-4 text-sm text-gray-500 sm:table-cell"><%= pollution_datum.nitric_oxide %></td>
  <td class="hidden px-3 py-4 text-sm text-gray-500 md:table-cell"><%= pollution_datum.nitrogen_dioxide %></td>
  <td class="px-3 py-4 text-sm text-gray-500"><%= pollution_datum.ozone %></td>
  <td class="px-3 py-4 text-sm text-gray-500"><%= pollution_datum.sulfur_dioxide %></td>
  <td class="px-3 py-4 text-sm text-gray-500"><%= pollution_datum.particulate_matter_2_5 %></td>
  <td class="px-3 py-4 text-sm text-gray-500"><%= pollution_datum.particulate_matter_10 %></td>
  <td class="px-3 py-4 text-sm text-gray-500"><%= pollution_datum.ammonia %></td>
  <td class="px-3 py-4 text-sm text-gray-500"><%= Time.at(pollution_datum.timestamp) %></td>
</tr>

app/views/pollution_data/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Pollution data</h1>
    <%= link_to "New pollution datum", new_pollution_datum_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="pollution_data" class="min-w-full">
    <%= render @pollution_data %>
  </div>
</div>

app/views/pollution_data/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @pollution_datum %>

    <%= link_to "Edit this pollution_datum", edit_pollution_datum_path(@pollution_datum), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this pollution_datum", pollution_datum_path(@pollution_datum), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to "Back to pollution_data", pollution_data_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="bg-gray-800">
  <div class="mx-auto max-w-7xl px-2 sm:px-6 lg:px-8">
    <div class="relative flex h-16 items-center justify-between">
      <div class="absolute inset-y-0 left-0 flex items-center sm:hidden">
        <!-- Mobile menu button-->
        <button type="button" class="relative inline-flex items-center justify-center rounded-md p-2 text-gray-400 hover:bg-gray-700 hover:text-white focus:outline-none focus:ring-2 focus:ring-inset focus:ring-white" aria-controls="mobile-menu" aria-expanded="false">
          <span class="absolute -inset-0.5"></span>
          <span class="sr-only">Open main menu</span>
          <!--
            Icon when menu is closed.

            Menu open: "hidden", Menu closed: "block"
          -->
          <svg class="block h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
          </svg>
          <!--
            Icon when menu is open.

            Menu open: "block", Menu closed: "hidden"
          -->
          <svg class="hidden h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
          </svg>
        </button>
      </div>
      <div class="flex flex-1 items-center justify-center sm:items-stretch sm:justify-start">
        <div class="flex flex-shrink-0 items-center">
          <img class="h-8 w-auto" src="https://tailwindui.com/img/logos/mark.svg?color=indigo&shade=500" alt="Your Company">
        </div>
        <div class="hidden sm:ml-6 sm:block">
          <div class="flex space-x-4">
            <!-- Current: "bg-gray-900 text-white", Default: "text-gray-300 hover:bg-gray-700 hover:text-white" -->
            <a href="#" class="bg-gray-900 text-white rounded-md px-3 py-2 text-sm font-medium" aria-current="page">Dashboard</a>
            <a href="#" class="text-gray-300 hover:bg-gray-700 hover:text-white rounded-md px-3 py-2 text-sm font-medium">Team</a>
            <a href="#" class="text-gray-300 hover:bg-gray-700 hover:text-white rounded-md px-3 py-2 text-sm font-medium">Projects</a>
            <a href="#" class="text-gray-300 hover:bg-gray-700 hover:text-white rounded-md px-3 py-2 text-sm font-medium">Calendar</a>
          </div>
        </div>
      </div>
      <div class="absolute inset-y-0 right-0 flex items-center pr-2 sm:static sm:inset-auto sm:ml-6 sm:pr-0">
        <button type="button" class="relative rounded-full bg-gray-800 p-1 text-gray-400 hover:text-white focus:outline-none focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-gray-800">
          <span class="absolute -inset-1.5"></span>
          <span class="sr-only">View notifications</span>
          <svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" d="M14.857 17.082a23.848 23.848 0 005.454-1.31A8.967 8.967 0 0118 9.75v-.7V9A6 6 0 006 9v.75a8.967 8.967 0 01-2.312 6.022c1.733.64 3.56 1.085 5.455 1.31m5.714 0a24.255 24.255 0 01-5.714 0m5.714 0a3 3 0 11-5.714 0" />
          </svg>
        </button>

        <!-- Profile dropdown -->
        <div class="relative ml-3">
          <div>
            <button type="button" class="relative flex rounded-full bg-gray-800 text-sm focus:outline-none focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-gray-800" id="user-menu-button" aria-expanded="false" aria-haspopup="true">
              <span class="absolute -inset-1.5"></span>
              <span class="sr-only">Open user menu</span>
              <img class="h-8 w-8 rounded-full" src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80" alt="">
            </button>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- Mobile menu, show/hide based on menu state. -->
  <div class="sm:hidden" id="mobile-menu">
    <div class="space-y-1 px-2 pb-3 pt-2">
      <!-- Current: "bg-gray-900 text-white", Default: "text-gray-300 hover:bg-gray-700 hover:text-white" -->
      <a href="#" class="bg-gray-900 text-white block rounded-md px-3 py-2 text-base font-medium" aria-current="page">Dashboard</a>
      <a href="#" class="text-gray-300 hover:bg-gray-700 hover:text-white block rounded-md px-3 py-2 text-base font-medium">Team</a>
      <a href="#" class="text-gray-300 hover:bg-gray-700 hover:text-white block rounded-md px-3 py-2 text-base font-medium">Projects</a>
      <a href="#" class="text-gray-300 hover:bg-gray-700 hover:text-white block rounded-md px-3 py-2 text-base font-medium">Calendar</a>
    </div>
  </div>
</nav>